import type {GetStaticPropsContext, NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/pagesStyle/Home.module.css'
import {useDispatch, useSelector} from "react-redux";
import {add, Idata} from "../redux/reducers/dataReducer/dataReducer";
import {useState} from "react";
import {useTranslations} from "next-intl";

const Home: NextPage = () => {
    const dispatch = useDispatch()
    const dataList: Idata[] = useSelector((state: any) => state.data.dataList)

    const t = useTranslations('home')

    const [inputVal , setInputVal] = useState<string>('')

  return (
    <div>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main} dir={'auto'}>
          <p>
              <span>
                  {t('dataTitle')}
              </span>
              <span>
                  {dataList.map((item,index) => index < dataList.length - 1 ? `${item},` : item)}
              </span>
          </p>
          <input onChange={(e)=> setInputVal(e.target.value)} value={inputVal}/>
          <button onClick={()=> inputVal.length > 0 && dispatch(add({data:inputVal}))}>{t('addDataBtnText')}</button>
      </main>
    </div>
  )
}

export default Home

export async function getStaticProps({locale}: GetStaticPropsContext) {
    return {
        props: {
            messages: (await import(`../messages/${locale}.json`)).default
        }
    };
}